### PR TITLE
- add Matroska (MKV) format support

### PR DESCRIPTION
**Pull request by SSE4**
this pull request add Matroska (MKV) format support into the VMF library http://matroska.org/technical/specs/index.html. reading VMF from file, adding VMF to the existing file and updating VMF in existing file - are supported. basically, code is adding new Tag element which contains XMP metadata as payload.

### CODE REVIEW

**Comment by apavlenko** [comment]
please note that MSVS 2013 can't build this code (due to `constexpr` and `noexcept`), my fix is at apavlenko/vmf@6e20d7770c2baedcb20cca52380e09928af1a4ec

**Comment by SSE4** [comment]
@apavlenko thanks a lot for catching and fixing, I've added your revision to my pull request.

**Comment by westernvillager** [comment]
I reviewed the code that implements MKV support in VMF code base. I compiled it on Windows and tested it with a few MKV files downloaded from internet. The samples I tested work fine. I also analyzed the metadata data block added into the MKV file. The implementation is very similar to that of MPG file format.

**Comment by hongwuwang** [comment]
I reviewed the code that implements MKV support in VMF code base. I compiled it on Windows and tested it with a few MKV files downloaded from internet. The samples I tested work fine. I also analyzed the metadata data block added into the MKV file. The implementation is very similar to that of MPG file format.

**Comment by hongwuwang** [comment]
I reviewed the code that implements MKV support in VMF code base. I compiled it on Windows and tested it with a few MKV files downloaded from internet. The samples I tested work fine. I also analyzed the metadata data block added into the MKV file. The implementation is very similar to that of MPG file format.

**Pull request merged**
